### ISSUE TITLE
Update Postman [auth]update-user-any-property - Remove username propName object

### ISSUE THREAD

**Issue by Ifycode** [collabocate-osc/tickets-ready-for-fixing#19]
#### Issue description

Probably forgot to remove the username propName object In the postman collection PATCH [auth]update-user-any-property body.

#

#### Steps to reproduce the issue

1. Go to [postman doc](https://documenter.getpostman.com/view/28471000/2sA3QmEaeB).
2. Then go to PATCH `[auth]update-user-any-property` request.
3. See that there's username object is there in the body, even though nothing about our auth uses username.

#

#### Expected result

Only the password propName object should be in the `[auth]update-user-any-property` body array.

#

#### Additional context

- Repo URL: https://github.com/collabo-community/backend-api-boilerplates

#

#### Testing checklist

Note (to contributor taking on this task assignment): Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] Only the password propName object should be in the `[auth]update-user-any-property` body array.
- [ ] I certify that I ran my checklist

#
> [!NOTE]  
> Just indicate here in the comment of this issue ticket that you are done, when you have completed the task.

**Comment by samuko-things** [comment]
@collabo-community/review-backend-api [@Ifycode ]
I have solve the issue as requested. Changes can be found in the postman documentation
- [x] Only the password propName object should be in the `[auth]update-user-any-property` body array.
- [x] I certify that I ran my checklist

**Comment by Ifycode** [comment]
Approved. Thank you for also including it in the documentation @samuko-things
