### ISSUE TITLE
Strip the Web Client of unused or no longer necessary resources

### ISSUE THREAD

**Issue by Ifycode** [collabocate-osc/tickets-ready-for-fixing#24]
#### Issue description

Web client needs cleanup for the fixes we are planning to release. The cleanup involves stripping the Web Client of unused or no longer necessary resources, files, pages etc.

#

#### Expected outcome

Remove the following from the Collabo Community App's web client code:
- Styled jsx: configurations, and any `.js` files that contain CSS code.
- Careers and donate pages in code-collabo app, and any files associated to them not used anywhere else in the application.

 #

#### Additional context

- Repo URL: https://github.com/collabo-community/web-client

#

#### Testing checklist

Note (to contributor taking on this task assignment): Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] Styled jsx configurations, and any `.js` files that contain CSS code have been removed.
- [ ] Careers and donate pages in code-collabo app, and any files associated to them not used anywhere else in the application have been removed.
- [ ] I certify that I ran my checklist

**Comment by Akpjunior94** [comment]
@Ifycode I want to clarify if it is just removing all and not worrying about how the UI will look or be affected?

**Comment by Ifycode** [comment]
Yes, don't worry about UI.
